default:
  build_type: "stable"
  announcement: ~

devel:
  inherits: default
  build_type: "development"
  announcement: 'Development version - use with caution. For stable version, please use the <a href="https://shiny.cytokineprofile.org/" target="_blank">stable version of the app</a>.'